export const RruleHelper = Object.freeze({
  LABELS: {
    FREQUENCY: 'Frequency',
    DUE_DATE: 'Due Date',
    SET_BY_DATE: 'SET BY DATE',
    SET_BY_DAY_OF_THE_MONTH: 'SET BY DAY OF THE MONTH',
    START_DATE: 'Start Date',
    END_DATE: 'End Date',
    WEEKLY_OPTION_TEXT: `Select the days of the week you'd like this SOP to be assigned`,
    MONTHLY_OPTION_TEXT: `Select the days of the month you'd like this SOP to be assigned`,
  },

  DEFAULT_FREQUENCY: [
    { label: 'One-Time', value: 0 },
    { label: 'Daily', value: 1 },
    { label: 'Weekly', value: 7 },
    { label: 'Monthly', value: 30 }
  ],

  FREQUENCY: [
    { label: 'One-Time (Read Only)', value: -1, interval: 0 },
    { label: 'One-Time', value: 0, interval: 0 },
    { label: 'Daily', value: 1, interval: 1 },
    { label: 'Weekly', value: 7, interval: 1 },
    { label: 'Bi-Weekly', value: 14, interval: 2 },
    { label: 'Monthly', value: 30, interval: 1 },
    { label: 'Bi-Monthly', value: 60, interval: 2 },
    { label: 'Quarterly', value: 90, interval: 3 },
    { label: 'Semiannual', value: 180, interval: 6 },
    { label: 'Annually', value: 365, interval: 1 },
  ],

  FREQUENCY_VALUES: {
    ONE_TIME: { label: 'One-Time', value: 0, valueString: '' },
    ONE_TIME_READ_ONLY: { label: 'One-Time', value: -1, valueString: '' },
    DAILY: { label: 'Daily', value: 1, valueString: 'DAILY' },
    WEEKLY: { label: 'Weekly', value: 7, valueString: 'WEEKLY' },
    BI_WEEKLY: { label: 'Bi-Weekly', value: 14, valueString: 'BI_WEEKLY' },
    MONTHLY: { label: 'Monthly', value: 30, valueString: 'MONTHLY' },
    BI_MONTHLY: { label: 'Bi-Monthly', value: 60, valueString: 'Bi_MONTHLY' },
    QUARTERLY: { label: 'Quarterly', value: 90, valueString: 'QUARTELY' },
    SEMI_ANNUALLY: { label: 'Semiannual', value: 180, valueString: 'SEMI_ANNUALLY' },
    ANNUALLY: { label: 'Annually', value: 365, valueString: 'ANNUALLY' },
  },

  WEEKS_TYPES: [
    { label: 'First', value: '1', id: 1 },
    { label: 'Second', value: '2', id: 2 },
    { label: 'Third', value: '3', id: 3 },
    { label: 'Fourth', value: '4', id: 4 },
    { label: 'Last', value: '-1', id: -1 }
  ],

  FULL_WEEK_DAYS: [
    { label: 'Sunday', value: 'SU' },
    { label: 'Monday', value: 'MO' },
    { label: 'Tuesday', value: 'TU' },
    { label: 'Wednesday', value: 'WE' },
    { label: 'Thursday', value: 'TH' },
    { label: 'Friday', value: 'FR' },
    { label: 'Saturday', value: 'SA' }
  ],

  WEEK_DAYS: [
    { rruleIndexNo: 6, label: 'S', value: 'Sunday', isSelected: false },
    { rruleIndexNo: 0, label: 'M', value: 'Monday', isSelected: false },
    { rruleIndexNo: 1, label: 'T', value: 'Tuesday', isSelected: false },
    { rruleIndexNo: 2, label: 'W', value: 'Wednesday', isSelected: false },
    { rruleIndexNo: 3, label: 'T', value: 'Thursday', isSelected: false },
    { rruleIndexNo: 4, label: 'F', value: 'Friday', isSelected: false },
    { rruleIndexNo: 5, label: 'S', value: 'Saturday', isSelected: false }
  ],

  MONTH_DAYS: [
    { rruleIndexNo: 1, label: '1', value: 1, isSelected: false },
    { rruleIndexNo: 2, label: '2', value: 2, isSelected: false },
    { rruleIndexNo: 3, label: '3', value: 3, isSelected: false },
    { rruleIndexNo: 4, label: '4', value: 4, isSelected: false },
    { rruleIndexNo: 5, label: '5', value: 5, isSelected: false },
    { rruleIndexNo: 6, label: '6', value: 6, isSelected: false },
    { rruleIndexNo: 7, label: '7', value: 7, isSelected: false },
    { rruleIndexNo: 8, label: '8', value: 8, isSelected: false },
    { rruleIndexNo: 9, label: '9', value: 9, isSelected: false },
    { rruleIndexNo: 10, label: '10', value: 10, isSelected: false },
    { rruleIndexNo: 11, label: '11', value: 11, isSelected: false },
    { rruleIndexNo: 12, label: '12', value: 12, isSelected: false },
    { rruleIndexNo: 13, label: '13', value: 13, isSelected: false },
    { rruleIndexNo: 14, label: '14', value: 14, isSelected: false },
    { rruleIndexNo: 15, label: '15', value: 15, isSelected: false },
    { rruleIndexNo: 16, label: '16', value: 16, isSelected: false },
    { rruleIndexNo: 17, label: '17', value: 17, isSelected: false },
    { rruleIndexNo: 18, label: '18', value: 18, isSelected: false },
    { rruleIndexNo: 19, label: '19', value: 19, isSelected: false },
    { rruleIndexNo: 20, label: '20', value: 20, isSelected: false },
    { rruleIndexNo: 21, label: '21', value: 21, isSelected: false },
    { rruleIndexNo: 22, label: '22', value: 22, isSelected: false },
    { rruleIndexNo: 23, label: '23', value: 23, isSelected: false },
    { rruleIndexNo: 24, label: '24', value: 24, isSelected: false },
    { rruleIndexNo: 25, label: '25', value: 25, isSelected: false },
    { rruleIndexNo: 26, label: '26', value: 26, isSelected: false },
    { rruleIndexNo: 27, label: '27', value: 27, isSelected: false },
    { rruleIndexNo: 28, label: '28', value: 28, isSelected: false },
    { rruleIndexNo: 29, label: '29', value: 29, isSelected: false },
    { rruleIndexNo: 30, label: '30', value: 30, isSelected: false },
    { rruleIndexNo: 31, label: '31', value: 31, isSelected: false },
    { rruleIndexNo: -1, label: 'Last Day', value: -1, isSelected: false }
  ],

  DAYS_OF_MONTH: [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    'Last Day'
  ],
})
  